<a href="https://colab.research.google.com/github/Massato01/Predicting-Soy-Deseases-Diagnosis/blob/main/soybean_NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Predicting Soy Deseade Diagnosis with NEURAL NETWORK***

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas                as pd
import numpy                 as np
from sklearn.preprocessing   import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics         import confusion_matrix, accuracy_score
from keras.models            import Sequential
from keras.layers            import Dense
from keras.utils             import np_utils

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Datasets/soybean.csv')

dataset.shape

(683, 36)

In [ ]:
dataset.head()

date plant-stand   precip  temp hail         crop-hist area-damaged  \
0  october      normal  gt-norm  norm  yes       same-lst-yr    low-areas   
1   august      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   
2     july      normal  gt-norm  norm  yes       same-lst-yr    scattered   
3     july      normal  gt-norm  norm  yes       same-lst-yr    scattered   
4  october      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   

     severity   seed-tmt germination  ... sclerotia fruit-pods fruit-spots  \
0  pot-severe       none      90-100  ...    absent       norm         dna   
1      severe  fungicide       80-89  ...    absent       norm         dna   
2      severe  fungicide       lt-80  ...    absent       norm         dna   
3      severe       none       80-89  ...    absent       norm         dna   
4  pot-severe       none       lt-80  ...    absent       norm         dna   

   seed mold-growth seed-discolor seed-size shriveling roots  \
0  norm      absent        absent      norm     absent  norm   
1  norm      absent        absent      norm     absent  norm   
2  norm      absent        absent      norm     absent  norm   
3  norm      absent        absent      norm     absent  norm   
4  norm      absent        absent      norm     absent  norm   

                   class  
0  diaporthe-stem-canker  
1  diaporthe-stem-canker  
2  diaporthe-stem-canker  
3  diaporthe-stem-canker  
4  diaporthe-stem-canker  

[5 rows x 36 columns]

In [ ]:
data = dataset.iloc[:, :35].values
target = dataset.iloc[:, 35].values

## ***Transforming the data into `Numeric` values***

In [ ]:
labelencoder = LabelEncoder()

target = labelencoder.fit_transform(target)

for d in data:
    d[:] = labelencoder.fit_transform(d[:])

In [ ]:
data = data.astype('float32')
data

array([[13., 12.,  7., ..., 11.,  3., 11.],
       [ 4., 12.,  9., ..., 11.,  3., 11.],
       [ 7., 11.,  6., ..., 10.,  2., 10.],
       ...,
       [ 5.,  7.,  0., ...,  0.,  0.,  9.],
       [ 3.,  7.,  0., ...,  0.,  0., 11.],
       [ 5.,  7.,  0., ...,  0.,  0., 11.]], dtype=float32)

## ***Formating class to `dummy`***

In [ ]:
target_dummy = np_utils.to_categorical(target, 19)
target_dummy

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

## ***Separating `train` and `test` data***

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data,
                                                    target_dummy,
                                                    test_size = 0.3,
                                                    random_state = 0)

print(len(X_train), len(X_test), len(y_train), len(y_test))

478 205 478 205


In [ ]:
X_train

array([[13.,  7.,  5., ...,  9.,  2.,  9.],
       [ 7., 11.,  6., ..., 10.,  3., 10.],
       [ 5., 13.,  7., ..., 12.,  1., 12.],
       ...,
       [15., 14.,  9., ..., 10., 16., 13.],
       [ 3., 11.,  9., ..., 14.,  2., 14.],
       [15., 11.,  6., ..., 10.,  2., 10.]], dtype=float32)

## ***Structuring the Neural Network***
> ### Structure: 35 - 36 - 36 - 36 - 19

In [ ]:
# Basic Neural Network Structure

neural_network = Sequential()

# 35 data inputs, and 19 targets
neural_network.add(Dense(units = 35, input_dim = 35))

neural_network.add(Dense(units = 36))

neural_network.add(Dense(units = 36))

# neural_network.add(Dense(units = 36))

neural_network.add(Dense(units = 19, activation = 'softmax'))

In [ ]:
neural_network.summary()

Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_95 (Dense)            (None, 35)                1260      
                                                                 
 dense_96 (Dense)            (None, 36)                1296      
                                                                 
 dense_97 (Dense)            (None, 36)                1332      
                                                                 
 dense_98 (Dense)            (None, 19)                703       
                                                                 
Total params: 4,591
Trainable params: 4,591
Non-trainable params: 0
_________________________________________________________________


In [ ]:
neural_network.compile(optimizer = 'adam',
                       loss = 'categorical_crossentropy',
                       metrics = ['accuracy'])

neural_network.fit(X_train, y_train, epochs = 1000,
                   validation_data = (X_test, y_test))

Epoch 1/1000
15/15 [==============================] - 0s 8ms/step - loss: 12.4461 - accuracy: 0.0941 - val_loss: 7.0119 - val_accuracy: 0.2244
Epoch 2/1000
15/15 [==============================] - 0s 2ms/step - loss: 5.3742 - accuracy: 0.2406 - val_loss: 4.6870 - val_accuracy: 0.2585
Epoch 3/1000
15/15 [==============================] - 0s 2ms/step - loss: 3.6183 - accuracy: 0.3494 - val_loss: 3.3997 - val_accuracy: 0.3463
Epoch 4/1000
15/15 [==============================] - 0s 2ms/step - loss: 2.5239 - accuracy: 0.4435 - val_loss: 2.4430 - val_accuracy: 0.4244
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.8151 - accuracy: 0.5544 - val_loss: 1.9454 - val_accuracy: 0.5512
Epoch 6/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.3916 - accuracy: 0.6339 - val_loss: 1.5663 - val_accuracy: 0.5756
Epoch 7/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.1488 - accuracy: 0.6799 - val_loss: 1.3148 - val_accuracy: 0.6244
Epoch

### ***Testing the Model***

In [ ]:
# Getting the predictions
predictions = neural_network.predict(X_test)

# Turning into boolean values
predictions = (predictions > 0.5)
predictions

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

## ***Accuracy***

In [ ]:
hit_rate = accuracy_score(predictions, y_test)
error_rate = 1 - hit_rate

print(f'HIT RATE: {hit_rate*100:.0f}%\nERROR RATE: {error_rate*100:.0f}%')

# GOOD PERFORMANCE

HIT RATE: 92%
ERROR RATE: 8%
